//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Framework.TimeKeeperServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:TimekeeperSOAP", ConfigurationName="TimeKeeperServiceReference.TimekeeperPort")]
    public interface TimekeeperPort {
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:Bushism#getProjects", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Framework.TimeKeeperServiceReference.TimekeeperSOAP getProjects(string user_hash);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="urn:Bushism#getProjects", ReplyAction="*")]
        System.IAsyncResult BegingetProjects(string user_hash, System.AsyncCallback callback, object asyncState);
        
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Framework.TimeKeeperServiceReference.TimekeeperSOAP EndgetProjects(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:Bushism#storeActivity", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="status")]
        Framework.TimeKeeperServiceReference.saveStatus storeActivity(string user_hash, string data);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="urn:Bushism#storeActivity", ReplyAction="*")]
        System.IAsyncResult BeginstoreActivity(string user_hash, string data, System.AsyncCallback callback, object asyncState);
        
        [return: System.ServiceModel.MessageParameterAttribute(Name="status")]
        Framework.TimeKeeperServiceReference.saveStatus EndstoreActivity(System.IAsyncResult result);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:TimekeeperSOAP")]
    public partial class TimekeeperSOAP : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string user_projectsField;
        
        private string activitiesField;
        
        /// <remarks/>
        public string user_projects {
            get {
                return this.user_projectsField;
            }
            set {
                this.user_projectsField = value;
                this.RaisePropertyChanged("user_projects");
            }
        }
        
        /// <remarks/>
        public string activities {
            get {
                return this.activitiesField;
            }
            set {
                this.activitiesField = value;
                this.RaisePropertyChanged("activities");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:TimekeeperSOAP")]
    public partial class saveStatus : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string statusField;
        
        /// <remarks/>
        public string status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("status");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface TimekeeperPortChannel : Framework.TimeKeeperServiceReference.TimekeeperPort, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class getProjectsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public getProjectsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public Framework.TimeKeeperServiceReference.TimekeeperSOAP Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((Framework.TimeKeeperServiceReference.TimekeeperSOAP)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class storeActivityCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public storeActivityCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public Framework.TimeKeeperServiceReference.saveStatus Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((Framework.TimeKeeperServiceReference.saveStatus)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TimekeeperPortClient : System.ServiceModel.ClientBase<Framework.TimeKeeperServiceReference.TimekeeperPort>, Framework.TimeKeeperServiceReference.TimekeeperPort {
        
        private BeginOperationDelegate onBegingetProjectsDelegate;
        
        private EndOperationDelegate onEndgetProjectsDelegate;
        
        private System.Threading.SendOrPostCallback ongetProjectsCompletedDelegate;
        
        private BeginOperationDelegate onBeginstoreActivityDelegate;
        
        private EndOperationDelegate onEndstoreActivityDelegate;
        
        private System.Threading.SendOrPostCallback onstoreActivityCompletedDelegate;
        
        public TimekeeperPortClient() {
        }
        
        public TimekeeperPortClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TimekeeperPortClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TimekeeperPortClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TimekeeperPortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public event System.EventHandler<getProjectsCompletedEventArgs> getProjectsCompleted;
        
        public event System.EventHandler<storeActivityCompletedEventArgs> storeActivityCompleted;
        
        public Framework.TimeKeeperServiceReference.TimekeeperSOAP getProjects(string user_hash) {
            return base.Channel.getProjects(user_hash);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BegingetProjects(string user_hash, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BegingetProjects(user_hash, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public Framework.TimeKeeperServiceReference.TimekeeperSOAP EndgetProjects(System.IAsyncResult result) {
            return base.Channel.EndgetProjects(result);
        }
        
        private System.IAsyncResult OnBegingetProjects(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string user_hash = ((string)(inValues[0]));
            return this.BegingetProjects(user_hash, callback, asyncState);
        }
        
        private object[] OnEndgetProjects(System.IAsyncResult result) {
            Framework.TimeKeeperServiceReference.TimekeeperSOAP retVal = this.EndgetProjects(result);
            return new object[] {
                    retVal};
        }
        
        private void OngetProjectsCompleted(object state) {
            if ((this.getProjectsCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.getProjectsCompleted(this, new getProjectsCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void getProjectsAsync(string user_hash) {
            this.getProjectsAsync(user_hash, null);
        }
        
        public void getProjectsAsync(string user_hash, object userState) {
            if ((this.onBegingetProjectsDelegate == null)) {
                this.onBegingetProjectsDelegate = new BeginOperationDelegate(this.OnBegingetProjects);
            }
            if ((this.onEndgetProjectsDelegate == null)) {
                this.onEndgetProjectsDelegate = new EndOperationDelegate(this.OnEndgetProjects);
            }
            if ((this.ongetProjectsCompletedDelegate == null)) {
                this.ongetProjectsCompletedDelegate = new System.Threading.SendOrPostCallback(this.OngetProjectsCompleted);
            }
            base.InvokeAsync(this.onBegingetProjectsDelegate, new object[] {
                        user_hash}, this.onEndgetProjectsDelegate, this.ongetProjectsCompletedDelegate, userState);
        }
        
        public Framework.TimeKeeperServiceReference.saveStatus storeActivity(string user_hash, string data) {
            return base.Channel.storeActivity(user_hash, data);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginstoreActivity(string user_hash, string data, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginstoreActivity(user_hash, data, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public Framework.TimeKeeperServiceReference.saveStatus EndstoreActivity(System.IAsyncResult result) {
            return base.Channel.EndstoreActivity(result);
        }
        
        private System.IAsyncResult OnBeginstoreActivity(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string user_hash = ((string)(inValues[0]));
            string data = ((string)(inValues[1]));
            return this.BeginstoreActivity(user_hash, data, callback, asyncState);
        }
        
        private object[] OnEndstoreActivity(System.IAsyncResult result) {
            Framework.TimeKeeperServiceReference.saveStatus retVal = this.EndstoreActivity(result);
            return new object[] {
                    retVal};
        }
        
        private void OnstoreActivityCompleted(object state) {
            if ((this.storeActivityCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.storeActivityCompleted(this, new storeActivityCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void storeActivityAsync(string user_hash, string data) {
            this.storeActivityAsync(user_hash, data, null);
        }
        
        public void storeActivityAsync(string user_hash, string data, object userState) {
            if ((this.onBeginstoreActivityDelegate == null)) {
                this.onBeginstoreActivityDelegate = new BeginOperationDelegate(this.OnBeginstoreActivity);
            }
            if ((this.onEndstoreActivityDelegate == null)) {
                this.onEndstoreActivityDelegate = new EndOperationDelegate(this.OnEndstoreActivity);
            }
            if ((this.onstoreActivityCompletedDelegate == null)) {
                this.onstoreActivityCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnstoreActivityCompleted);
            }
            base.InvokeAsync(this.onBeginstoreActivityDelegate, new object[] {
                        user_hash,
                        data}, this.onEndstoreActivityDelegate, this.onstoreActivityCompletedDelegate, userState);
        }
    }
}
